### ISSUE TITLE
this.ui.write() is not a function

### ISSUE THREAD

**Issue by tunnckoCore** [enquirer/prompt-base#1]
Errors comes from `confirm` and `autocomplete` and possibly  more.

```
~/dev/enquirer/examples master ✓  
% 1 ❯ node autocomplete.js                                                                            September 12, 01:12:02
? Select a state to travel from Kansasreadline.js:953
            throw err;
            ^

TypeError: this.ui.write is not a function
    at Prompt.onSubmit (/home/charlike/dev/enquirer/examples/plugins/autocomplete.js:109:11)
    at UI.Emitter.emit (/home/charlike/dev/enquirer/node_modules/component-emitter/index.js:133:20)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:188:7)
    at Interface._onLine (readline.js:232:10)
    at Interface._line (readline.js:574:8)
    at Interface._ttyWrite (readline.js:851:14)
    at ReadStream.onkeypress (readline.js:119:10)
    at emitTwo (events.js:111:20)
    at ReadStream.emit (events.js:191:7)
```

and

```
~/dev/enquirer/examples master ✓  
% ❯ node confirm.js                                                                                   September 12, 01:14:23
? Foo? Noreadline.js:953
            throw err;
            ^

TypeError: this.ui.write is not a function
    at Confirm.onSubmit (/home/charlike/dev/enquirer/examples/node_modules/enquirer-prompt-confirm/index.js:71:11)
    at UI.on (/home/charlike/dev/enquirer/node_modules/component-emitter/index.js:65:8)
    at UI.Emitter.emit (/home/charlike/dev/enquirer/node_modules/component-emitter/index.js:133:20)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:188:7)
    at Interface._onLine (readline.js:232:10)
    at Interface._line (readline.js:574:8)
    at Interface._ttyWrite (readline.js:851:14)
    at ReadStream.onkeypress (readline.js:119:10)
    at emitTwo (events.js:111:20)
```

**Comment by tunnckoCore** [comment]
Actually, sorry. It's more because they are older than latest `prompt-base`. I'll look if I can PR to them.

**Comment by jonschlinkert** [comment]
I have a lot to push up too, maybe wait for that before you spend too much time. I can try tomorrow (I have something else to push up - hopefully tonight ;)

**Comment by tunnckoCore** [comment]
> I have a lot to push up too, maybe wait for that before you spend too much time.

Great. I just tried and failed, so yea. :D 

I'm just thinking to use it in `npm-hooks`. :) https://github.com/tunnckoCore/ideas/issues/34

**Comment by jonschlinkert** [comment]
lol yeah this took some time to get familiar with how everything works. I'm planning on adding more docs for creating custom prompts

**Comment by jonschlinkert** [comment]
I can't reproduce these errors, I'm assuming whatever was causing this was fixed, or it was incorrect configuration. If you still have the error, please reopen the issue with example code. We can't debug from error messages alone. thanks
